### ISSUE TITLE
Add services section

### ISSUE THREAD

**Issue by jguillermo0426** [JarrettTo/JiuStudios#1]
Change the **features** section of the template to the offered services

![Screenshot 2024-05-22 173538](https://github.com/JarrettTo/JiuStudios/assets/135218283/a520e5e3-f35d-4f25-99e3-af3c6698ef08)

[Link to docs with info](https://docs.google.com/document/d/1xZrfhy5D_RjwDNUwkJvE9VkoL7VpI9DonJVZckXlhd0/edit)

**Comment by GithubSim13** [comment]
![image](https://github.com/JarrettTo/JiuStudios/assets/144484430/ab47bfd2-7244-4076-9dfb-6608cd798ff7)
