### ISSUE TITLE
Add get started section

### ISSUE THREAD

**Issue by jguillermo0426** [JarrettTo/JiuStudios#3]
Replace the get started section with the write up

![Screenshot 2024-05-22 174037](https://github.com/JarrettTo/JiuStudios/assets/135218283/6a127aa9-d952-4ba1-9150-1cc23a1e55bc)

[Link to docs with info](https://docs.google.com/document/d/1xZrfhy5D_RjwDNUwkJvE9VkoL7VpI9DonJVZckXlhd0/edit)

**Comment by GithubSim13** [comment]
Fixed width
